## Pytorch Funadamentals

Resource : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
print("I am definetly completing this pytorch course")

I am definetly completing this pytorch course


In [2]:
!nvidia-smi #To check which GPU we are actually using

Sat Oct  5 14:12:46 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.09                 Driver Version: 561.09         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0              6W /   75W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [78]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__) # to check the version of the pytorch

2.4.1+cu121


## Creating Tensors
Pytorch Tensors are created using - https://pytorch.org/docs/stable/tensors.html

In [9]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [12]:
#Get tensor back as python int
scalar.item()

7

In [14]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([2])

In [17]:
# Matrix (Use upper case)
MATRIX = torch.tensor([[10,11],[14,15]])
MATRIX

tensor([[10, 11],
        [14, 15]])

In [24]:
MATRIX.ndim
MATRIX[0]
MATRIX[1]
MATRIX.shape

torch.Size([2, 2])

In [25]:
#Tensor (Use upper case)
TENSOR = torch.tensor([[[1,0,45],
                        [2,1,81],
                        [9,10,11]]])
TENSOR

tensor([[[ 1,  0, 45],
         [ 2,  1, 81],
         [ 9, 10, 11]]])

In [26]:
TENSOR.ndim

3

In [27]:
TENSOR.shape 

torch.Size([1, 3, 3])

In [30]:
TENSOR[0]

tensor([[ 1,  0, 45],
        [ 2,  1, 81],
        [ 9, 10, 11]])

## Random Tensors
why random tensors?

Random tensors are important the way many neural networks learn is that they start with tesnors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random number - look at data - update random numbers - look at data and so on`

In [47]:
#Create a random tensor of size (4,5)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0173, 0.7999, 0.4733, 0.6609],
        [0.7729, 0.1025, 0.2641, 0.2506],
        [0.1721, 0.6386, 0.9124, 0.2519]])

In [39]:
random_tensor.ndim

3

In [41]:
#create random tensors similar to a image tensor
random_image_size_tensor = torch.rand(size = (3, 224,224)) #colour channels(R,G,B) ,height and width
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [48]:
#creating tensors of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [49]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [50]:
#create tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [51]:
ones.dtype

torch.float32

In [52]:
random_tensor.dtype

torch.float32

## createing a range of tensors and tensors-like

In [59]:
one_to_15 = torch.arange(start= 0, end = 1000, step = 50)
one_to_15

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [63]:
#creating tensors like
ten_zeroes = torch.rand_like(input = one_to_15.float())
ten_zeroes


<bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x0000026AE6BC5D50>>

## Tensor datatypes
Note : Tensor datatypes is one of the 3 big error in DL with pytorch
1. Tensor not right datatype
2. Tensor not right shape
3. Tensors not on the right device

In [88]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,4.5,8.9],dtype=None, #what data types is the tensor, can change it with dtype= torch.float16 and so on
                               device=None, #what device tesnor is on
                               requires_grad=False) #whether or not gradients for tensors operations
float_32_tensor


tensor([3.0000, 4.5000, 8.9000])

In [74]:
float_32_tensor.dtype

torch.float16

In [89]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3.0000, 4.5000, 8.8984], dtype=torch.float16)

## Getting info from tensors (tensor attributes)
1. Tensor not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shape from tensor use `tensor.shape`
3. Tensors not on the right device - to get device `tensor.device`

In [91]:
summa_tensor = torch.rand(3,4)
summa_tensor

tensor([[0.5680, 0.4976, 0.4868, 0.9058],
        [0.6116, 0.7744, 0.3701, 0.0527],
        [0.8368, 0.9548, 0.2569, 0.7833]])

In [93]:
#Find out details about some tensor
print(summa_tensor)
print(f"data_type_tensor: {summa_tensor.dtype}")
print(f"shape_of_tensor: {summa_tensor.shape}")
print(f"device_of_tensor: {summa_tensor.device}")

tensor([[0.5680, 0.4976, 0.4868, 0.9058],
        [0.6116, 0.7744, 0.3701, 0.0527],
        [0.8368, 0.9548, 0.2569, 0.7833]])
data_type_tensor: torch.float32
shape_of_tensor: torch.Size([3, 4])
device_of_tensor: cpu


## Manipulating tensors (tensors operation)

Tensors operation include :
1. Addition
2. Subtraction
3. Multiplication (Element- wise)
4. Division 
5. Matrix Multiplication

In [94]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [96]:
#Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [97]:
#Sub 10
tensor - 10

tensor([-9, -8, -7])

In [98]:
#Try out Pytorch inbuilt
torch.mul(tensor,10)

tensor([10, 20, 30])