## Pytorch Funadamentals

Resource : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
print("I am definetly completing this pytorch course")

I am definetly completing this pytorch course


In [2]:
!nvidia-smi #To check which GPU we are actually using

Sat Oct  5 14:12:46 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.09                 Driver Version: 561.09         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0              6W /   75W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__) # to check the version of the pytorch

2.4.1+cu121


## Creating Tensors
Pytorch Tensors are created using - https://pytorch.org/docs/stable/tensors.html

In [9]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [12]:
#Get tensor back as python int
scalar.item()

7

In [14]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([2])

In [17]:
# Matrix (Use upper case)
MATRIX = torch.tensor([[10,11],[14,15]])
MATRIX

tensor([[10, 11],
        [14, 15]])

In [24]:
MATRIX.ndim
MATRIX[0]
MATRIX[1]
MATRIX.shape

torch.Size([2, 2])

In [25]:
#Tensor (Use upper case)
TENSOR = torch.tensor([[[1,0,45],
                        [2,1,81],
                        [9,10,11]]])
TENSOR

tensor([[[ 1,  0, 45],
         [ 2,  1, 81],
         [ 9, 10, 11]]])

In [26]:
TENSOR.ndim

3

In [27]:
TENSOR.shape 

torch.Size([1, 3, 3])

In [30]:
TENSOR[0]

tensor([[ 1,  0, 45],
        [ 2,  1, 81],
        [ 9, 10, 11]])

## Random Tensors
why random tensors?

Random tensors are important the way many neural networks learn is that they start with tesnors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random number - look at data - update random numbers - look at data and so on`

In [47]:
#Create a random tensor of size (4,5)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0173, 0.7999, 0.4733, 0.6609],
        [0.7729, 0.1025, 0.2641, 0.2506],
        [0.1721, 0.6386, 0.9124, 0.2519]])

In [39]:
random_tensor.ndim

3

In [41]:
#create random tensors similar to a image tensor
random_image_size_tensor = torch.rand(size = (3, 224,224)) #colour channels(R,G,B) ,height and width
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [48]:
#creating tensors of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [49]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [50]:
#create tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [51]:
ones.dtype

torch.float32

In [52]:
random_tensor.dtype

torch.float32